ALTER TABLE buildings ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE floors ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE floors ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE units ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE units ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE owners ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE owners ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE floor_owners ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE floor_owners ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE leases ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE leases ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE lease_units ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE lease_units ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE occupancies ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE occupancies ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE common_areas ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE common_areas ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE repair_records ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE repair_records ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';

ALTER TABLE repair_attachments ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'system';
ALTER TABLE repair_attachments ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT 'system';
